import { jwtVerify } from 'jose';
import Cookies from 'cookies';
import type { NextPage, GetServerSideProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import styles from '../styles/Home.module.css'

import pg from '../lib/pg';
import { getRemoteJWKSet } from '../lib/oidc';

import { listBlogPreviews } from '../query/blog';
import type { BlogPostPreview } from '../query/blog';


const Home: NextPage<{ posts: BlogPostPreview[] }> = ({ posts }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sample Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Sample Blog!
        </h1>

        { 
          posts.map(post => (
            <p key={post.id} className={styles.description} >
              <Link href={`/blogpost/${post.id}`}>{post.title}</Link>
            </p>
          ))
        }
      </main>
    </div>
  )
}


export const getServerSideProps: GetServerSideProps = async ({ req }) => {
  const authorised = req.cookies['oauth-access-token'] ? !!await jwtVerify(req.cookies['oauth-access-token'], await getRemoteJWKSet()) : false;

  const { rows } = await pg.query(listBlogPreviews.compile({ authorised }));

  return {
    props: {
      posts: rows
    },
  }
}


export default Home;
